spring:
  sql:
    init:
      platform: postgres
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:postgresql://localhost:5432/registration
    username: myuser
    password: secret
    driverClassName: org.postgresql.Driver

  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher   